[versions]
netflixDgs = "12.0.1"
spotless = "8.10.2"
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"

[libraries]
netflix-dgs = { module = "com.netflix.graphql.dgs:graphql-dgs-platform-dependencies", version.ref = "netflixDgs" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }