name: Gradle Build

on:
  pull_request:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    name: "Build with Gradle"
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: read
    strategy:
      matrix:
        include:
          - repo: central
            pulpogatoVersion: 3.1.0
          - repo: github
            pulpogatoVersion: 3.1.0
          - repo: jitpack
            pulpogatoVersion: main-SNAPSHOT
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/actions/wrapper-validation@v6
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: zulu
          cache: gradle
      - uses: gradle/actions/setup-gradle@v6
      - run: >-
          ./gradlew -Prepo=${{ matrix.repo }} \
              -Pgpr.user=${{ env.GITHUB_ACTOR }} \
              -Pgpr.key=${{ secrets.GITHUB_TOKEN }} \
              -PpulpogatoVersion=${{ matrix.pulpogatoVersion }} \
              build
